sudo: false
language: node_js
node_js:
- '8'
os:
  # - osx # still too slow
  - linux
services:
  - xvfb
addons:
  apt:
    packages:
      - libsecret-1-dev
matrix:
  fast_finish: true
branches:
  only:
    - master
    - /^greenkeeper-.*$/
    - /^greenkeeper/.*$/
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never

install:
  - yarn
  - yarn vscode:prepublish
before_script: 'yarn linter'
script: 'yarn test'
#after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
