sudo: false
language: node_js
node_js:
- '8'
os:
  # - osx # still too slow
  - linux
addons:
  apt:
    packages:
      - libsecret-1-dev
matrix:
  fast_finish: true
branches:
  only:
    - master
    - /^greenkeeper-.*$/
    - /^greenkeeper/.*$/
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
install:
  - yarn
  - yarn vscode:prepublish
before_script: 'yarn linter'
script: 'yarn test'
#after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
