name: Ship js trigger release

on:
  push:
    branches: [master]

jobs:
  trigger_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: |
          yarn install
      - run: |
          yarn shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
          NPM_AUTH_TOKEN: ""
