name: Ship js prepare release

on:
  issue_comment:
    types: [created]

jobs:
  prepare_release:
    if: |
      github.event_name == 'issue_comment' &&
      (github.event.comment.author_association == 'member' || github.event.comment.author_association == 'owner') &&
      startsWith(github.event.comment.body, '@shipjs prepare')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - uses: actions/setup-node@v2
      - run: |
          yarn install
      - run: |
          git config --global user.email "mail@markus-wolf.de"
          git config --global user.name "Markus Wolf"
      - run: yarn shipjs prepare --yes --no-browse
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  create_done_comment:
    if: success()
    needs: prepare_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v5.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@${{ github.actor }} `shipjs prepare` done'
            })

  create_fail_comment:
    if: cancelled() || failure()
    needs: prepare_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v5.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@${{ github.actor }} `shipjs prepare` fail'
            })
